services:
    pushDevices:
        class: ekreative\PushBundle\Service\Devices
        arguments:
          - "@snsClient"
          - "%aws_platform_arns%"
    pushMessages:
        class: ekreative\PushBundle\Service\Messages
        arguments:
          - "@snsClient"
          - "%aws_platform_arns%"
          - "@logger"
    snsClient:
        class: Aws\Sns\SnsClient
        factory_class: Aws\Sns\SnsClient
        factory_method: factory
        arguments:
          -
            key: "%aws_key%"
            secret: "%aws_secret%"
            region: "%aws_region%"
